server:
  port: 8001





spring:
  application:
    name: springcloud-itemManage-8001

  datasource:

    url: jdbc:mysql://localhost:3306/manage?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8&allowPublicKeyRetrieval=true

    driver-class-name: com.mysql.cj.jdbc.Driver

    username: root

    password: 020701czp


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-itemManage-8001




